QUB-ASL/bzzz

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/pull_request_template.md
GitHub templates for PRs and issues
> Github templates

- CONTRIBUTING.md
First version of `contributing.md`: 
- Working with git (branches, PRs, issues, etc)
- Good coding practice and naming conventions in C++ and Python
- Project structure
- Documentation
- Unit testing
[View the file](https://github.com/QUB-ASL/bzzz/blob/feature/contributing/CONTRIBUTING.md)
> New contributing guidelines

- hardware/tests/hw_test_motors.cpp
- include/config.hpp
- include/motors.hpp
- include/radio.hpp
- src/main.cpp
- src/motors.cpp
- src/radio.cpp
* Add TorqueSystem (motor) class
* Updated `hw_test_motors.cpp`
* Fixed radio errors
> Add TorqueSystem (motor) class, fixed radio issues

- include/config.hpp
- include/radio.hpp
- src/main.cpp
- src/radio.cpp
- check arming switch in setup
- check kill switch in loop
- disarm and exit loop if killed
Note: We also need to kill when there is no signal from the radio (perhaps in a different PR)
- Addresses #29
> Implementation of fail-safes

- README.md
- Added project description to `README.md`
- Added link to demo video
- Closes #33
> Update README.md (project description and demo)

- include/controller.hpp
- src/controller.cpp
- src/main.cpp
- Clipping signals to motors
- Introducing function `motorPwmSignals` in `controller`
- Closes #26
> Clip singals to motors

- platformio.ini
- src/main.cpp
- Create function `waitForPiSerial` in main
- Waiting for Raspberry Pi to send data over serial
- Remove RC_ESC as a dependency from platformio.ini
- May partially address #28
> Waiting for Raspberry Pi to send data

- src/main.cpp
Added `initialAngularVelocity` in `main.cpp` which is then subtract  from the `measuredAngularVelocity` to give the `angularVelocityCorrected` which is used for the `controlAction`
- Addresses #43
> Initial angular velocities

- SAFETY.md
`SAFETY.md` is introduced: a document that attempts to identify the key hazards in the lab (e.g., soldering, handling LiPo batteries, and working with quadcopter motors) and propose a number of safety measures.
> Safety instructions (SAFETY.md)

- CHANGELOG.md
- Introduced `CHANGELOG.md` file
> Changelog file

- src/radio.cpp
Deleted `mapRadioToAngle` and `mapTrimmerToPercentage` functions from `radio.cpp`.
> Cleaned up `radio.cpp`

- raspberry/data/README.md
- raspberry/main.py
- add slicing before appending to caches
- update `data/README.md` (docs on the format of logs)
We have recorded data during manual flight only and everything seems to work OK.
> Hotfix of logging system

- hardware/tests/README.md
Fix typos in `hardware/tests/README.md`
> Fix typos in README

- README.md
Added the new altitude hold video on YouTube to the main README
- Closes #121
> Update README.md (added altitude hold video)

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/ISSUE_TEMPLATE/documentation_issue.yml
- .github/ISSUE_TEMPLATE/questions.yml
Remove affected file name and line requirement
> Update Issue templates 

- include/ahrs.hpp
> fix typos in ahrs.hpp

- docs/SETUP.md
- raspberry/main.py
Fixed typos in [raspberry/main.py](https://github.com/QUB-ASL/bzzz/blob/dev/raspberry/main.py)
Fixed link in [SETUP.md](https://github.com/QUB-ASL/bzzz/blob/dev/docs/SETUP.md)
- Closes #152
- Addresses #154
> Documentation issues and typos

- raspberry/bzzz/sensors/anemometer.py
- Data acquisition happens in background
- Data are kept in a buffer
- API documentation (not complete - Jamie, I'm leaving the rest to you)
```python
with Anemometer() as sensor:
for _i in range(20):
print(sensor.all_sensor_data)
```
Here we choose a data processor and a window length
```python
processor = AverageFilter()
with Anemometer(window_length=5, data_processor=processor) as sensor:
for i in range(20):
time.sleep(0.1)
print(sensor.all_sensor_data)
```
> Read anemometer data in background

- .github/ISSUE_TEMPLATE/bug_report.yml
Remove the requirement for some section.
only section 'Describe the bug' is required.
I think its best if this is merged into main, what's your thoughts?
- Closes #166
> Update issue bug_report.

- include/config.hpp
The ESC and buzzer pins have been updated in the `config.hpp` file to match the new PCB's
This has been tested on Quadcopter and works
> Update ESC and buzzer pins 

- raspberry/bzzz/read_sbus/read_sbus_from_GPIO_receiver.py
A few more comments have been added to explain what certain functions and parameters do.
- Addresses #118
tested on quadcopter, it does not effect the quadcopter
> Improve some of the documentation in read_sbus_from_GPIO_receiver.py

- docs/SETUP.md
Updated documentation for remote access to bzzz via ssh using user and host names
- Closes #191 
This method has been tested and works to ssh into the Pi on the quadcopter
> Update SETUP.md for remote access

- include/config.hpp
- src/main.cpp
implementation of a timer ISR to guarantee that the main loop on the ESP32 runs at a fixed rate.
- Closes #37
This has been tested on the quadcopter
> Timer interrupt ISR 

- raspberry/bzzz/sensors/evo_time_of_flight.py
- raspberry/bzzz/sensors/pressure_sensor.py
- raspberry/main.py
The threading now begins on the main file. 
- Closes #196 
- Closes #188 
- Closes #186
Has been tested on the quadcopter and all the sensors are collecting the data.
> Initiate threading on main file

- CHANGELOG.md
Before we merge #158 we need to update the `CHANGELOG`.
> Update CHANGELOG before merging dev into main

- CHANGELOG.md
> Changelog: add link to v100

- include/config.hpp
- src/main.cpp
Update attitude gains
tested on quadcopter
> Hard-coding attitude gainz

- docs/SAFETY.md
Pre-flight tests in `SAFETY.md`
> Pre-flight tests in safety.md
